name: Run Task on ${{ github.event.inputs.env }}
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "development"

jobs:
  run-task:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}
    steps:
      - run: echo test

